### PR TITLE
Sprint 2 task

### PR DESCRIPTION
**Pull request by desali**

### CODE REVIEW

**Comment by desali** [comment]
> Its better right
> If a > b:
> Return a
> 
> Return b
> 
> Why do you need else

I think with else looks good and easy for reading

**Comment by desali** [comment]
> Python developer use underscore, not CamelCase
> So max_number is right not mazNumber

I will review my code(

**Comment by desali** [comment]
> Then you have added .pyc file which is compiled python file. Its better to create .gitignore file and list it therr, or ignore them during creating commit.

ok

**Comment by An4ik** [comment]
And the last and final thing. 
We have to keep it  as task for other students maybe next year i dont know
But we have our answer package to do comparison etc.

So please move your files to answer module. It woild be nice and the I will accept your MR

**Pull request merged**
